modLoader="javafml"
loaderVersion="47,)"
license="All rights reserved"
[[mods]]
modId="deepblue"
version="${1.1.1}"
displayName="DragN's Aquatics: Deep Blue Addon"
logoFile="deepblue.png"
authors="DragN0007"
description='''
An addon for DragN's Bettas & Aquatics. Adds large marine animals and commercial aquarium decor!
'''
[[dependencies.deepblue]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.deepblue]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.deepblue]]
    modId="geckolib"
    mandatory=true
    versionRange = "[4.4.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deepblue]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.1.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deepblue]]
    modId = "bettas"
    mandatory = true
    versionRange = "[1.2.3,)"
    ordering="NONE"
    side="BOTH"